### PR TITLE
fix issue #5

### PR DESCRIPTION
**Pull request by daaaabeen**
fix issue #5 
fix when i use two fingers touch  screen, camera unexpected

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hi my friend,
Can you add an example please? Check the [current examples](https://github.com/jdnichollsc/Phaser-Kinetic-Scrolling-Plugin/tree/master/examples)
Thank you for your contribution, Nicholls

**Comment by daaaabeen** [comment]
OK

**Comment by jdnichollsc** [comment]
@daaaabeen Hi bro, let me accept the previous pull request to accept your changes. Can you rename your excellent example to *6*? 👍 
Also, can you modify the README to add you as collaborator with your info? 🥇 
Let me know what you think, Nicholls

**Comment by jdnichollsc** [comment]
@daaaabeen Hi my friend, sorry for the delay!
Can you fix the conflicts to merge your changes?
Thanks in advance, Nicholls

**Comment by daaaabeen** [comment]
done~ @jdnichollsc

**Comment by jdnichollsc** [comment]
@daaaabeen thanks for your contribution! 🥇

**Pull request merged**
