### PR TITLE
Phaser 3 support

### PR DESCRIPTION
**Pull request by insideone**
I'm new to Phaser and could miss something. Examples are scratchy on the edges, but work.
It's TypeScript now, since I can't stomach anything else.

### CODE REVIEW

**Comment by jdnichollsc** [comment]
@insideone I think it would be better if you publish your changes as another npm package with another repository, and I can update this package for phaser-ce, what do you think mate?

**Comment by jdnichollsc** [comment]
Also, if you want I can create that repository for you as part of @proyecto26, let me know what you think :)

**Comment by insideone** [comment]
@jdnichollsc As I can see there still is a lot of interest in Phaser 2 , so maybe splitting packages is a right thing to do.
Alright, so I'll close PR and publish something like **phaser-3-kinetic-scrolling-plugin**.

I think it will be better to keep phaser-3 package as a fork until it goes mature. In the first place I've created this PR to share the working package-solution (I don't like the idea to copy-paste gists like [this](https://gist.github.com/PaNaVTEC/ef18d2bee239514515e91d6c50012825) in my projects), so anyone could use it in ease and send PR updates.

**Comment by jdnichollsc** [comment]
@insideone let me know the npm package/GitHub repo in order to add that reference from the README of this project, thanks! :)

**Pull request closed without merging**
